/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sqcexbbrvqbfqfnzxjxh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxY2V4YmJydnFiZnFmbnp4anhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTU4MjksImV4cCI6MjA3Njk5MTgyOX0.oKAGxsn-UntBQ9iRzS-CuPfqxmrw8wuEBUDlt-zQFIQ"